# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  # - name: Featured Article
  #   url: /#featured-article #与/content下直接_index.md中设定的表示符对应
  #   weight: 20
  - name: Working Paper
    url: /#working-paper
    weight: 25
  - name: Publication
    url: /#publication
    weight: 30
  # - name: Talks # event文件下
  #   url: /#talks
  #   weight: 40
  - name: Lecture
    url: /#lecture  #看展示成那种，类似一条一条的就在_index.md中做成post，放在post文件夹里
    weight: 45
  # - name: News
  #   url: /#news #post文件夹
  #   weight: 50
  # - name: Experience
  #   url: experience/  #experience文件
  #   weight: 60
  # - name: Projects
  #   url: projects/  #projects文件。因为content下的_index.md文件中block内容没有project，所以主页面不显示，而是链接跳转。
  #   weight: 70
  # - name: Teaching
  #   url: teaching/  #/content/teaching下的_index.md文件，
  #   weight: 80
